# Generated by Django 5.2.9 on 2026-01-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_studentprofile_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
