# Generated by Django 5.2.9 on 2026-01-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_studentprofile_raw_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non-binary"),
                    ("genderqueer", "Genderqueer"),
                    ("genderfluid", "Gender fluid"),
                    ("agender", "Agender"),
                    ("transgender_male", "Transgender male"),
                    ("transgender_female", "Transgender female"),
                    ("intersex", "Intersex"),
                    ("two_spirit", "Two-spirit"),
                    ("prefer_not_to_say", "Prefer not to say"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("completed", "Completed"),
                    ("inactive", "Inactive"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="student_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
