# Generated by Django 5.2.9 on 2026-01-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_studentprofile_email_studentprofile_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="profile_picture",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
