# Generated by Django 5.2.9 on 2026-01-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_studentprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="enrollment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="expected_graduation",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
