# Generated by Django 5.2.13 on 2026-09-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_delete_course_delete_grade_and_more'),
        ('users', '0006_alter_studentprofile_enrollment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='user',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
