# Generated by Django 5.2.8 on 2026-01-01 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MagnetConfig",
            fields=[
                (
                    "command_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("description", models.TextField(default="")),
                ("requires_interaction", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("instructions", models.JSONField(default=list)),
            ],
        ),
    ]
