# Generated by Django 5.2.8 on 2026-01-01 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
        ("magnet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="magnetconfig",
            name="institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institution_magnet_configs",
                to="institutions.institution",
            ),
        ),
    ]
