# Generated by Django 5.2.8 on 2026-01-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
        ("magnet", "0002_magnetconfig_institution"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MagnetConfig",
            new_name="MagnetScrappingCommand",
        ),
    ]
