# Generated by Django 5.2.9 on 2026-01-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magnet", "0003_rename_magnetconfig_magnetscrappingcommand"),
    ]

    operations = [
        migrations.AddField(
            model_name="magnetscrappingcommand",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
