# Generated by Django 5.2.9 on 2026-01-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magnet', '0004_magnetscrappingcommand_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magnetscrappingcommand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
