# Generated by Django 5.2.7 on 2025-11-09 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=255)),
                ('exam_date', models.DateField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=50, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedule', to='courses.semesterinfo')),
            ],
        ),
    ]
