# Generated by Django 5.2.8 on 2025-12-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examtimetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='course_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
