# Generated by Django 5.2.9 on 2026-01-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('examtimetable', '0002_alter_examschedule_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='course_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='examschedule',
            constraint=models.UniqueConstraint(fields=('course_code', 'institution_id', 'semester'), name='unique_exam_schedule', nulls_distinct=False),
        ),
    ]
