# Generated by Django 5.2.7 on 2025-11-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examtimetable', '0002_examschedule_campus_examschedule_coordinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='institution_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
