# Generated by Django 5.2.9 on 2026-03-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examtimetable', '0003_alter_examschedule_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='datetime_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
