# Generated by Django 5.2.9 on 2026-04-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_institution'),
        ('examtimetable', '0004_examschedule_datetime_str'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['institution_id', 'semester', 'course_code'], name='examtimetab_institu_6cadef_idx'),
        ),
    ]
