# Generated by Django 5.2.13 on 2026-05-26 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examtimetable', '0006_remove_examschedule_building_and_more'),
        ('institutions', '0002_alter_institution_state_province'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examschedule',
            name='unique_exam_schedule',
        ),
        migrations.RemoveIndex(
            model_name='examschedule',
            name='examtimetab_institu_6cadef_idx',
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='hrs',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='institution_id',
            field=models.ForeignKey(db_column='institution_id', default=5426, on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='institutions.institution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='venue',
            field=models.CharField(default='Venue', max_length=255),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='examschedule',
            old_name='institution_id',
            new_name='institution',
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='institutions.institution'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['institution', 'semester', 'course_code'], name='examtimetab_institu_6cadef_idx'),
        ),
        migrations.AddConstraint(
            model_name='examschedule',
            constraint=models.UniqueConstraint(fields=('course_code', 'institution', 'semester'), name='unique_exam_schedule', nulls_distinct=False),
        ),
    ]
