# Generated by Django 5.2.13 on 2026-05-26 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examtimetable', '0006_remove_examschedule_building_and_more'),
        ('institutions', '0002_alter_institution_state_province'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='examschedule',
            new_name='examtimetab_institu_06de37_idx',
            old_name='examtimetab_institu_6cadef_idx',
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='hrs',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='institution_id',
            field=models.ForeignKey(default=5426, on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='institutions.institution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='venue',
            field=models.CharField(default='Venue', max_length=255),
            preserve_default=False,
        ),
    ]
