# Generated by Django 5.2.13 on 2026-08-31 13:32

import django.db.models.deletion
import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_institution'),
        ('users', '0006_alter_studentprofile_enrollment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_label', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(upload_to=notes.models.note_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='courses.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.user')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
