# Generated by Django 5.2.13 on 2026-08-31 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('users', '0006_alter_studentprofile_enrollment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_outputs', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=16)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='notes.note')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
