# Generated by Django 5.2.13 on 2026-09-11 09:40

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='converted_file',
            field=models.FileField(blank=True, upload_to=notes.models.note_upload_path),
        ),
    ]
