# Generated by Django 5.2.13 on 2026-09-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_note_converted_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="converted_file",
        ),
    ]
