# Generated by Django 5.2.13 on 2026-09-19 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lecturer_studentcourse_remove_course_institution_and_more'),
        ('notes', '0005_remove_note_converted_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='course',
        ),
        migrations.AddField(
            model_name='note',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='courses.studentcourse'),
        ),
    ]
