# Generated by Django 5.2.13 on 2026-09-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='converted_markdown',
            field=models.TextField(blank=True, default=''),
        ),
    ]
