# Generated by Django 5.2.13 on 2026-09-21 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_converted_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='question_format',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('flashcard', 'flashcard'), ('mcq', 'mcq'), ('open_ended', 'open_ended')], max_length=16)),
                ('questions', models.JSONField()),
                ('prompt_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_sets', to='notes.generationjob')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='notes.note')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
