# Generated by Django 5.2.13 on 2026-09-21 13:32

import django.db.models.deletion
import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_generationjob_question_format_questionset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('script', models.TextField()),
                ('audio', models.FileField(upload_to=notes.models.podcast_upload_path)),
                ('duration_seconds', models.FloatField(default=0)),
                ('tts_provider', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts', to='notes.generationjob')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='notes.note')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
