"""
Django settings for professor project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_path = Path(__file__).resolve().parent.parent / ".env"
load_dotenv(dotenv_path=env_path)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-7^6*%@5)80f-6obitpqk$$&l91(^lu19@$hway2=f=^lfv%z--"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", False)

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "event_bus",
    "institutions",
    "courses",
    "examtimetable",
    "users",
    "magnet",
]


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": "%(asctime)s [%(levelname)s: %(message)s"},
        "json": {
            "()": "professor.log_formatter.StandardJSONLogFormatter",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "professor": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Rabbit mq setup
RABBITMQ_USER = os.getenv("RABBITMQ_USER", None)
RABBITMQ_PASSWORD = os.getenv("RABBITMQ_PASSWORD", None)
RABBITMQ_HOST = os.getenv("RABBITMQ_HOST", None)
RABBITMQ_PORT = os.getenv("RABBITMQ_PORT", None)
RABBITMQ_VHOST = os.getenv("RABBITMQ_VHOST", None)

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 30,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "professor.verisafe_jwt_authentication.VerisafeJWTAuthentication",
    ],
}

MIDDLEWARE = [
    "professor.middlewares.request_logging_middleware.RequestLoggingMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "professor.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "professor.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "professor"),
        "USER": os.getenv("DB_USER", "asdfghjkljsdfadfgj"),
        "PASSWORD": os.getenv("DB_PASSWORD", "sdfgkhldgsfASZFxgjkhfdgsxg"),
        "HOST": os.getenv("DB_HOST", "professor-db-rw.production.svc.cluster.local"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", None)
assert AWS_ACCESS_KEY_ID is not None, "AWS_ACCESS_KEY_ID was not set in .env!"

AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", None)
assert AWS_ACCESS_KEY_ID is not None, "AWS_SECRET_ACCESS_KEY was not set in .env!"

AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", None)
assert AWS_ACCESS_KEY_ID is not None, "AWS_STORAGE_BUCKET_NAME was not set in .env!"

AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", None)
assert AWS_S3_REGION_NAME is not None, "AWS_S3_REGION_NAME was not set in .env!"

AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"


# For serving static files directly from S3
AWS_S3_URL_PROTOCOL = "https:"
AWS_S3_USE_SSL = True
AWS_S3_VERIFY = True

STATIC_URL = "static/"
MEDIA_URL = "/media/"

ENVIRONMENT = os.getenv("ENVIRONMENT", "dev")

STORAGE_LOCATION = "professor-media"

if ENVIRONMENT == "prod":
    STORAGE_LOCATION = "professor-media"
elif ENVIRONMENT == "staging":
    STORAGE_LOCATION = "qa-professor-media"
else:
    STORAGE_LOCATION = "dev-professor-media"

print(AWS_S3_CUSTOM_DOMAIN)

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "location": STORAGE_LOCATION,
            "querystring_auth": False,
            "default_acl": None,
            "custom_domain": AWS_S3_CUSTOM_DOMAIN,
            "url_protocol": "https:",
            "signature_version": "s3v4",
            "querystring_expire": 3600,
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "location": "static",
            "querystring_auth": False,
            "default_acl": None,
            "signature_version": "s3v4",
            "querystring_expire": 3600,
            "custom_domain": AWS_S3_CUSTOM_DOMAIN,
            "url_protocol": AWS_S3_URL_PROTOCOL,
        },
    },
}


# File upload settings for large images
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# HTTPS Configuration
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_TLS = os.environ.get("USE_TLS", "False").lower() == "true"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# AUTH_USER_MODEL = "users.User"
