# Generated by Django 5.2.7 on 2025-11-18 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0002_remove_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_scale',
            field=models.CharField(choices=[('letter', 'Letter'), ('gpa_4', 'GPA 4.0'), ('gpa_5', 'GPA 5.0'), ('percentage', 'Percentage'), ('pass_fail', 'Pass/Fail')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9),
        ),
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_status', models.CharField(blank=True, default='enrolled', max_length=50, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course_enrollments', to='courses.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course_enrollments', to='courses.semesterinfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_course_enrollments', to='users.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
    ]
