# Generated by Django 5.2.13 on 2026-09-19 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_institution'),
        ('institutions', '0002_alter_institution_state_province'),
        ('notes', '0005_remove_note_converted_file'),
        ('users', '0006_alter_studentprofile_enrollment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('term_label', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('term_start_date', models.DateField(blank=True, null=True)),
                ('term_end_date', models.DateField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institutions.institution')),
                ('previous_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_attempts', to='courses.studentcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.AlterUniqueTogether(
            name='studentcourseenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentcourseenrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='semester',
        ),
        migrations.DeleteModel(
            name='ScheduleEntry',
        ),
        migrations.RemoveField(
            model_name='studentcourseenrollment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studentcourseenrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='student',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='student_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='courses.studentcourse'),
        ),
    ]
