# Generated by Django 5.2.13 on 2026-09-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lecturer_studentcourse_remove_course_institution_and_more'),
        ('notes', '0006_alter_note_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='StudentCourseEnrollment',
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
        migrations.AddIndex(
            model_name='studentcourse',
            index=models.Index(fields=['student', 'archived_at'], name='courses_stu_student_e227af_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcourse',
            index=models.Index(fields=['institution'], name='courses_stu_institu_3dd56f_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturer',
            index=models.Index(fields=['student_course'], name='courses_lec_student_4ea703_idx'),
        ),
    ]
