# Generated by Django 5.2.13 on 2026-09-29 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_delete_course_delete_grade_and_more"),
        ("users", "0007_remove_credentials_user_delete_administrator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourse",
            name="color",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="studentcourse",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="studentcourse",
            unique_together={("student", "idempotency_key")},
        ),
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=9,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("venue", models.CharField(blank=True, max_length=255, null=True)),
                ("campus", models.CharField(blank=True, max_length=255, null=True)),
                ("section", models.CharField(blank=True, max_length=100, null=True)),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                ("color", models.CharField(blank=True, max_length=9, null=True)),
                ("is_recurring", models.BooleanField(default=True)),
                ("specific_date", models.DateField(blank=True, null=True)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to="courses.studentcourse",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
                "indexes": [
                    models.Index(
                        fields=["student_course"], name="courses_sch_student_665d29_idx"
                    )
                ],
                "unique_together": {("student_course", "idempotency_key")},
            },
        ),
    ]
