# Generated by Django 5.2.9 on 2026-01-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="state_province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
